const Catchasyncerror = fn =>{
    console.log(fn);
}

module.exports = Catchasyncerror